source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

inhibit_all_warnings!

pod 'AFNetworking', '2.5.0'
pod 'MTLFMDBAdapter', '0.1.8'
pod 'ReactiveCocoa', '2.4.2'
pod 'ReactiveViewModel', '0.3'
pod 'Mantle', '1.5.1'
pod 'OpenUDID', '1.0.0'
pod 'IQKeyboardManager', '3.2.1.1'
pod 'NSString-Hashes', '1.2.2'
pod 'ActionSheetPicker-3.0', '1.6.2'
pod 'ASValueTrackingSlider'
pod 'ISO8601DateFormatter', '0.7'
pod 'Masonry', '0.6.1'
pod 'RMPickerViewController', '1.3.2'
pod 'UIColor-Hex', '0.1.1'
pod 'SVPullToRefresh', '0.4.1'
pod 'REFormattedNumberField', '1.1.5'
pod 'SVProgressHUD', '1.1.3'
pod 'Fabric', '1.5.4'
pod 'Crashlytics', '3.3.3'
pod 'KGModal', '1.1.0'
pod 'ZSWTappableLabel', '1.1'
pod 'ZSWTaggedString', '1.1'
pod 'MWPhotoBrowser', '2.1.1'
pod 'SHSPhoneComponent', '2.15'
pod 'ZXingObjC', '3.1.0'
pod 'CZPhotoPickerController', :git => 'https://github.com/objczl/CZPhotoPickerController', :commit => '486dc83'
pod 'MSPageViewController', :git => 'https://github.com/mindsnacks/MSPageViewController', :commit => '0259bc2'
#pod 'BugshotKit', :git => 'https://github.com/marcoarment/BugshotKit', :commit => 'e982a2a'

target 'Tests', :exclusive => true do
    pod 'OCMockito', '2.0.1'
end
