#!/bin/bash
# Script to compile and run unit tests from the command line

PROVISIONINGP_ROFILE="$1"

if [[ $PROVISIONINGP_ROFILE == '' ]]; then
  echo 'ERROR: Missing the required $PROVISIONINGP_ROFILE argument.';
  exit;
fi

find_pattern () {
    ls -d $1 2>/dev/null | head -n 1
}

BUILD_DIR=$(pwd)/build
BUILD_VERSION=`cat VERSION`

XCWORKSPACE=$(find_pattern "*.xcworkspace")
XCODEPROJ=$(find_pattern "*.xcodeproj")

sh $(pwd)/script/clean

if [[ $XCWORKSPACE == '' ]]; then
	SCHEME=`echo $XCODEPROJ | awk -F '.xcodeproj' '{print $1}'`
	ARCHIVE_PATH=$BUILD_DIR/Archive/$SCHEME
	xctool -project $XCODEPROJ -scheme $SCHEME -sdk iphoneos clean archive -archivePath $ARCHIVE_PATH -derivedDataPath $BUILD_DIR
	xcodebuild -exportArchive -archivePath $ARCHIVE_PATH.xcarchive -exportPath $ARCHIVE_PATH.ipa -exportFormat ipa -exportProvisioningProfile $PROVISIONINGP_ROFILE  | xcpretty
	mv $BUILD_DIR/Archive/$SCHEME.ipa $BUILD_DIR/Archive/$SCHEME-$BUILD_VERSION.ipa
else
	SCHEME=`echo $XCWORKSPACE | awk -F '.xcworkspace' '{print $1}'`
	ARCHIVE_PATH=$BUILD_DIR/Archive/$SCHEME
	xctool -workspace $XCWORKSPACE -scheme $SCHEME -sdk iphoneos clean archive -archivePath $ARCHIVE_PATH -derivedDataPath $BUILD_DIR
	xcodebuild -exportArchive -archivePath $ARCHIVE_PATH.xcarchive -exportPath $ARCHIVE_PATH.ipa -exportFormat ipa -exportProvisioningProfile $PROVISIONINGP_ROFILE  | xcpretty
	mv $BUILD_DIR/Archive/$SCHEME.ipa $BUILD_DIR/Archive/$SCHEME-$BUILD_VERSION.ipa
fi

