#!/bin/bash
# Script to compile and run unit tests from the command line

PROVISIONINGP_ROFILE="$1"

if [[ $PROVISIONINGP_ROFILE == '' ]]; then
  echo 'ERROR: Missing the required $PROVISIONINGP_ROFILE argument.';
  exit;
fi

find_pattern () {
    ls -d $1 2>/dev/null | head -n 1
}

BUILD_DIR=$(pwd)/build
XCWORKSPACE=$(find_pattern "*.xcworkspace")
SCHEME=`echo $XCWORKSPACE | awk -F '.xcworkspace' '{print $1}'`
ARCHIVE_PATH=$BUILD_DIR/Archive/$SCHEME
BUILD_VERSION=`cat VERSION`

echo "========================================================================="
echo "script cleaning"
echo "========================================================================="

sh $(pwd)/script/clean

echo "========================================================================="
echo "xctool -workspace $XCWORKSPACE -scheme $SCHEME -sdk iphoneos clean archive -archivePath $ARCHIVE_PATH -derivedDataPath $BUILD_DIR"
echo "========================================================================="

xctool -workspace $XCWORKSPACE -scheme $SCHEME -sdk iphoneos clean archive -archivePath $ARCHIVE_PATH -derivedDataPath $BUILD_DIR

echo "========================================================================="
echo "xcodebuild -exportArchive -archivePath $ARCHIVE_PATH.xcarchive -exportPath $ARCHIVE_PATH.ipa -exportFormat ipa -exportProvisioningProfile $PROVISIONINGP_ROFILE  | xcpretty"
echo "========================================================================="

xcodebuild -exportArchive -archivePath $ARCHIVE_PATH.xcarchive -exportPath $ARCHIVE_PATH.ipa -exportFormat ipa -exportProvisioningProfile $PROVISIONINGP_ROFILE  | xcpretty
mv $BUILD_DIR/Archive/$SCHEME.ipa $BUILD_DIR/Archive/$SCHEME-$BUILD_VERSION.ipa
