#! /bin/bash

SUBMODULE="$1"

if [[ ! -f "README.md" ]]; then
	mkdir Vendor
	mkdir Classes
	mkdir Resources
	touch README.md

	# Copy Configurations files
	cp Script/config/Podfile Podfile
	cp Script/config/gitignore .gitignore
	
	if [[ $SUBMODULE == 'submodule' ]]; then
		sh Script/ext/github-quick-submodules.sh
	elif [[ ! -n $SUBMODULE ]]; then
		sh Script/ext/github-quick-dependencies.sh
  else
	  echo 'ERROR: Missing the required submodule argument.';
	  exit
	fi

	echo "=============================================================================="
	pod install --no-repo-update

	echo "=============================================================================="
	echo ""
	echo "Config Xcode Build Phases"
	echo ""
	echo "objclean \"\${SRCROOT}/Script/brsp/xcode-objclean-warnings.sh\""
	echo "todo \"\${SRCROOT}/Script/brsp/xcode-todo-warnings.sh\""
	echo ""
	echo "=============================================================================="
	exit
fi

# git submodules update
git submodule update --init --recursive
# CocoaPods install
pod install --no-repo-update

