#! /bin/bash

if [[ ! -f "README.md" ]]; then
	mkdir Vendor
	mkdir Classes
	mkdir Resources
	touch README.md

	# Copy Configurations files
	cp Script/config/Podfile Podfile
	cp Script/config/gitignore .gitignore

	sh Script/utils/github-quick-submodules.sh
	pod install --no-repo-update

	echo ""
	echo "config Xcode Build Phases"
	echo "objclean \"\${SRCROOT}/Script/brsp/xcode-objclean-warnings.sh\""
	echo "todo \"\${SRCROOT}/Script/brsp/xcode-todo-warnings.sh\""
	exit
fi

# git submodules update
git submodule update --init --recursive
# CocoaPods install
pod install --no-repo-update

