#!/bin/bash
# Script to compile and run unit tests from the command line

BUILD_DIR=$(pwd)/build

find_pattern () {
    ls -d $1 2>/dev/null | head -n 1
}

XCWORKSPACE=$(find_pattern "*.xcworkspace")
SCHEME=`echo $XCWORKSPACE | awk -F '.xcworkspace' '{print $1}'`

echo "========================================================================="
echo "xctool -workspace $XCWORKSPACE -scheme $SCHEME clean"
echo "========================================================================="

xctool -workspace $XCWORKSPACE -scheme $SCHEME clean

echo "========================================================================="
echo "rm -rf $BUILD_DIR"
echo "========================================================================="

rm -rf $BUILD_DIR

echo "========================================================================="
echo 'DerivedData Cleaning...'
echo "========================================================================="

rm -rf ~/Library/Developer/Xcode/DerivedData/*

echo 'Done'
ls -l ~/Library/Developer/Xcode/DerivedData
