#!/bin/bash
# Script to compile and run unit tests from the command line

BUILD_DIR=$(pwd)/build

find_pattern () {
    ls -d $1 2>/dev/null | head -n 1
}

XCWORKSPACE=$(find_pattern "*.xcworkspace")
XCODEPROJ=$(find_pattern "*.xcodeproj")

if [[ $XCWORKSPACE == '' ]]; then
	SCHEME=`echo $XCODEPROJ | awk -F '.xcodeproj' '{print $1}'`
	xctool -project $XCODEPROJ -scheme $SCHEME clean
else
	SCHEME=`echo $XCWORKSPACE | awk -F '.xcworkspace' '{print $1}'`
	xctool -workspace $XCWORKSPACE -scheme $SCHEME clean
fi

echo "========================================================================"

echo "Build cleaning..."

rm -rf $BUILD_DIR

echo 'DerivedData Cleaning...'

rm -rf ~/Library/Developer/Xcode/DerivedData/*
ls -l ~/Library/Developer/Xcode/DerivedData

echo "========================================================================"
