#!/bin/bash
# Script to compile and run unit tests from the command line

BUILD_DIR=$(pwd)/build

find_pattern () {
    ls -d $1 2>/dev/null | head -n 1
}

XCWORKSPACE=$(find_pattern "*.xcworkspace")
XCODEPROJ=$(find_pattern "*.xcodeproj")
SCHEME=`echo $XCWORKSPACE | awk -F '.xcworkspace' '{print $1}'`

sh $(pwd)/script/clean

if [[ $XCWORKSPACE == '' ]]; then
	SCHEME=`echo $XCODEPROJ | awk -F '.xcodeproj' '{print $1}'`
	xctool -project $XCODEPROJ -scheme $SCHEME -sdk iphonesimulator CONFIGURATION_BUILD_DIR=$BUILD_DIR build
else
	SCHEME=`echo $XCWORKSPACE | awk -F '.xcworkspace' '{print $1}'`
	xctool -workspace $XCWORKSPACE -scheme $SCHEME -sdk iphonesimulator CONFIGURATION_BUILD_DIR=$BUILD_DIR build
fi

echo "========================================================================="
echo "ios-sim launch build/$SCHEME.app --devicetypeid 'com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 9.1' --exit"
echo "========================================================================="

# ios-sim launch build/Example.app --devicetypeid 'com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 9.1'
ios-sim launch $BUILD_DIR/$SCHEME.app --devicetypeid 'com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 9.2' --exit