#!/bin/bash
# Script to compile and run unit tests from the command line

find_pattern () {
    ls -d $1 2>/dev/null | head -n 1
}

XCWORKSPACE=$(find_pattern "*.xcworkspace")
XCODEPROJ=$(find_pattern "*.xcodeproj")
SCHEME=`echo $XCWORKSPACE | awk -F '.xcworkspace' '{print $1}'`

sh $(pwd)/script/clean

if [[ $XCWORKSPACE == '' ]]; then
	SCHEME=`echo $XCODEPROJ | awk -F '.xcodeproj' '{print $1}'`
	xctool -project $XCODEPROJ -scheme $SCHEME -sdk iphonesimulator test
else
	SCHEME=`echo $XCWORKSPACE | awk -F '.xcworkspace' '{print $1}'`
	xctool -workspace $XCWORKSPACE -scheme $SCHEME -sdk iphonesimulator test
fi

